---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

     #Set up passwordless sudo for deploy
    - name: Make sure we have a 'wheel' group
      become: yes
      group:
        name: wheel
        state: present
   
    - name: Allow wheel group to have passwordless sudo
      become: yes
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    - name: Create a deploy user
      become: yes
      user:
        name: deploy
        password: Change666Me #Needs to be encrypted
        groups: 
        - sudo
        - wheel
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        createhome: yes        # Defaults to yes
        home: /home/deploy  # Defaults to /home/<username>
        
    - name: Set up authorized keys
      become: yes
      authorized_key:
        user: deploy
        state: present
        key: '{{ item }}'
      with_file:
        - '../Ansible/files/keys/ssh/id_rsa.pub' 

    - name: Install required packages
      apt:
        pkg:
          - ansible
          - mysql-server
          - git
          - python3-pip
        state: latest
        update_cache: true

    - name: copy private key
      ansible.builtin.copy:
        src: ../Ansible/files/keys/ssh/id_rsa   
        dest: /home/deploy/.ssh/id_rsa
        owner: deploy
        group: deploy
        mode: '0600' 